### ISSUE TITLE
uniref90 taxids

### ISSUE THREAD

**Issue by evolgenomology** [reubwn/hgt#1]
Hi Reuben,

there are apparently TaxIDs in the uniref90.fasta file:
```
>UniRef90_Q197F8 Uncharacterized protein 002R n=1 Tax=Invertebrate iridescent virus 3 TaxID=345201 RepID=002R_IIV3
```
No need to parse the xml the Sujai way anymore I guess.

Cheers

P

**Comment by reubwn** [comment]
Ah great, thanks for the heads up!
