### ISSUE TITLE
R script trees

### ISSUE THREAD

**Issue by jensbast** [reubwn/hgt#3]
Hey Reuben,

thanks for your very awesome HGT pipe.
As a note:
To get the taxify output to work, we had to use diamond blast with the blast table out-format, otherwise it did not want to take the diamond binary.

We are running into issues with the R script for evaluating the trees:

Rscript ./hgt/analyse_trees.R -p ./1_On_b1v03.mafft_alns/treefiles/ -f test.pdf
Tue Jun  9 14:21:20 2020 -- analyse_trees.R
Error in grep(opt$query, tr$tip.label) : invalid 'pattern' argument
Execution halted

Any idea why and how this could be solved? Maybe a R version thing?

edit: sorry had the wrong output (this is now the error we encounter)

**Comment by reubwn** [comment]
Hi Jens! No problem, glad they are useful.

RE the diamond issue - yes I think diamond changed the default output a bit maybe a year ago, so I am not surprised there are now a few bugs (I should check the scripts again). I think the script makes a call to `diamond view` but perhaps something is broken now.

For the analyse_trees.R script - I think you need to provide the program with some identifier that allows it to identify the focal ("query") tip, via the `--query` parameter. For example, I usually name the proteins with some 4 letter code (e.g. "DMEL|g1234.t1" etc), so in this case I would specify 

```
Rscript analyse_trees.R -p /path/to/trees/ -q DMEL
```

and the program uses `grep` to find that name in each treefile. The program needs to know which is the focal sequence to compute the stats, and also highlights it with a different colour in the output PDF. Sorry, that should be a required parameter!

On top of that, there may well be R version issues too - it was a while ago I wrote the script and R loves to break...

Let me know if that helps,
Cheers,
Reuben

**Comment by jensbast** [comment]
Nice!
That indeed solved it.

BTW: it looks like some of our old asexual mites have more HGT then the sexual ones (but overall <3%). We need more pairs to compare to really know though.
